### PR TITLE
A lot of changes

### PR DESCRIPTION
**Pull request by joshcangit**
I made another version that works a bit better but I did a lot changes.
I sort of tested every function I have changed to confirm this indeed works, as is.
However if you don't want all the changes, I might need to redo some or many changes again.

### CODE REVIEW

**Comment by dybdeskarphet** [comment]
Just two things:
* [Line 495](https://github.com/dybdeskarphet/privacy-redirector/pull/30/commits/6adac30297a6d6670e82293b36f1e826b2be5530#diff-11505857bfdf30fb93c4477a2b1ee790e87152508f8be0d1dae2743f3d34f8a4L495), ```window.location.pathname !== "/"``` was intentional, scirbe.rip doesn't redirect to user pages, this condition was written for the sake of continuity
* Is it tested overall? Because there are a lot of changes as the title says.

Other than that, this is gorgeous, thank you so much for your effort and contribution. ❤️

**Comment by dybdeskarphet** [comment]
Also, can I add your username to the [credits](https://github.com/dybdeskarphet/privacy-redirector?tab=readme-ov-file#-credits)?

**Comment by joshcangit** [comment]
> * [Line 495](https://github.com/dybdeskarphet/privacy-redirector/pull/30/commits/6adac30297a6d6670e82293b36f1e826b2be5530#diff-11505857bfdf30fb93c4477a2b1ee790e87152508f8be0d1dae2743f3d34f8a4L495), ```window.location.pathname !== "/"``` was intentional, scirbe.rip doesn't redirect to user pages, this condition was written for the sake of continuity

I think that condition just excludes the homepage.
I'll need to figure out a condition that actually exclude user pages.

**Comment by dybdeskarphet** [comment]
> > * [Line 495](https://github.com/dybdeskarphet/privacy-redirector/pull/30/commits/6adac30297a6d6670e82293b36f1e826b2be5530#diff-11505857bfdf30fb93c4477a2b1ee790e87152508f8be0d1dae2743f3d34f8a4L495), ```window.location.pathname !== "/"``` was intentional, scribe.rip doesn't redirect to user pages, this condition was written for the sake of continuity
> 
> I think that condition just excludes the homepage.
> I'll need to figure out a condition that actually exclude user pages.
> 
> Also btw, yes you can add my username to the credits.

So apparently Medium changed the user name URLs from `username.medium.com/` to  `medium.com/@username`. I'll add it after merging this PR. Thank you again.

**Comment by joshcangit** [comment]
> It has both `username.medium.com/` and `medium.com/@username` URLs. I'll add it after merging this PR. Thank you again.

Sorry, I just figured out how to do it now.
It's in my commit, c33a2fe.

**Pull request merged**
